FROM public.ecr.aws/lambda/python:3.12

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy function code
COPY main.py .

# Set the CMD to your handler
CMD ["main.lambda_handler"]
